#!/bin/bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ./ ~/ ~/REPOS/ -mindepth 1 -maxdepth 5 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

# Imprime el comando cd al directorio seleccionado
echo "cd '$selected'; clear; ls"
